version: "3.8"

services:
  app:
    build: .
    container_name: shop-review-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped 